# Streamlit Cloud Secrets Configuration
# Copy this content to your Streamlit Cloud app's secrets section

[secrets]
# CRITICAL: Replace with your actual RapidAPI key
PINNACLE_API_KEY = "your_actual_rapidapi_key_here"

# API Configuration
PINNACLE_HOST = "pinnacle-odds.p.rapidapi.com"
CACHE_DURATION = "5"
REQUEST_TIMEOUT = "30"

# Betting Configuration
BANKROLL = "1000.0"
KELLY_FRACTION = "0.25"
MAX_BET_PERCENTAGE = "0.05"

# Application Configuration
LOG_LEVEL = "INFO"
DATA_DIR = "Données"

# Instructions:
# 1. Go to your Streamlit Cloud dashboard
# 2. Select your app
# 3. Click "Settings" → "Secrets"
# 4. Copy the [secrets] section above (without the comments)
# 5. Replace "your_actual_rapidapi_key_here" with your real API key
# 6. Save the secrets configuration